// examples/nextjs/app/page.tsx
'use client';

import { useAccount, useConnect, useDisconnect } from 'wagmi';
import { useState } from 'react';
import { useFhevm, useFhevmEncrypt, useFhevmPublicDecrypt, useFhevmUserDecrypt, FhevmClientStatus, FhevmCacheType } from '@fhevm/react-sdk';
import {
  sendIncrementTx,
  getUserCounterHandle,
  getPublicCounterHandle,
} from '@/lib/contracts/counter';
import { LOCALHOST_COUNTER_ADDRESS } from '@/config/localhost';
import { SEPOLIA_COUNTER_ADDRESS } from '@/config/sepolia';

export default function Home() {
  const { address, isConnected, chain } = useAccount();
  const { connect, connectors } = useConnect();
  const { disconnect } = useDisconnect();
  const { client, status, isReady, network: mode } = useFhevm();

  const contractAddress = mode === 'localhost' ? LOCALHOST_COUNTER_ADDRESS : SEPOLIA_COUNTER_ADDRESS;
  const { createInput } = useFhevmEncrypt({ contractAddress });
  const { decrypt: publicDecrypt } = useFhevmPublicDecrypt();
  const { decrypt: userDecrypt, clearCache } = useFhevmUserDecrypt({ contractAddress, cacheType: FhevmCacheType.Persistent });

  const [userValue, setUserValue] = useState<string>('-');
  const [publicValue, setPublicValue] = useState<string>('-');
  const [loading, setLoading] = useState<string>('');
  const [txStatus, setTxStatus] = useState<string>('');

  // Network validation
  const expectedChainId = mode === 'localhost' ? 31337 : 11155111; // Localhost: 31337, Sepolia: 11155111
  const isWrongNetwork = isConnected && chain && chain.id !== expectedChainId;
  const expectedNetworkName = mode === 'localhost' ? 'Localhost (31337)' : 'Sepolia Testnet';

  const handleDisconnect = async () => {
    // Clear signature cache on disconnect
    await clearCache();
    disconnect();
  };

  const handleIncrement = async (type: 'user' | 'public') => {
    if (!client || !address) return;
    
    // Set loading state first and force UI update
    setLoading(`increment-${type}`);
    setTxStatus('⏳ Encrypting value...');
    
    // Small delay to ensure UI updates before encryption starts
    await new Promise(resolve => setTimeout(resolve, 0));

    try {
      // Create encrypted input
      const input = createInput(address);
      input.add32(1); // Increment by 1
      const encrypted = await input.encrypt();

      setTxStatus('⏳ Sending transaction...');
      await sendIncrementTx(encrypted.handles[0], encrypted.inputProof, type, mode);

      setTxStatus(`✓ ${type === 'user' ? 'User' : 'Public'} counter incremented successfully!`);
      setTimeout(() => setTxStatus(''), 3000);
    } catch (err) {
      console.error('Increment error:', err);
      setTxStatus('✗ Transaction failed');
      setTimeout(() => setTxStatus(''), 3000);
    } finally {
      setLoading('');
    }
  };

  const handleDecryptUser = async () => {
    if (!client || !address) return;
    setLoading('decrypt-user');
    setUserValue('⏳ Decrypting...');

    try {
      const handle = await getUserCounterHandle(mode);
      const value = await userDecrypt(handle);
      setUserValue(value.toString());
    } catch (err) {
      console.error('Decrypt error:', err);
      setUserValue('✗ Error');
    } finally {
      setLoading('');
    }
  };

  const handleDecryptPublic = async () => {
    if (!client) return;
    setLoading('decrypt-public');
    setPublicValue('⏳ Decrypting...');

    try {
      const handle = await getPublicCounterHandle(mode);
      const value = await publicDecrypt(handle);
      setPublicValue(value.toString());
    } catch (err) {
      console.error('Decrypt error:', err);
      setPublicValue('✗ Error');
    } finally {
      setLoading('');
    }
  };

  return (
    <main className="container">
      <div className="card">
        <h1 style={{ textAlign: 'center' }}>FHEVM SDK Next.js Demo</h1>
        <p className="subtitle">
          Build confidential applications with Fully Homomorphic Encryption
        </p>
        <p style={{ textAlign: 'center', fontSize: '0.875rem', opacity: 0.7, marginTop: '0.5rem' }}>
          Network: <strong>{mode === 'sepolia' ? 'Sepolia Testnet' : 'Localhost'}</strong>
        </p>
        
        {/* Wallet Connection */}
        <section className="section">
          <h2>1. Connect Wallet</h2>
          {!isConnected ? (
            <button 
              onClick={() => connect({ connector: connectors[0] })}
              className="btn-primary"
            >
              Connect Wallet
            </button>
          ) : (
            <div className="wallet-info">
              <div style={{ flex: 1 }}>
                <p style={{ marginBottom: '0.25rem', fontSize: '0.875rem', opacity: 0.7 }}>Connected Address</p>
                <p className="wallet-address">{address?.slice(0, 8)}...{address?.slice(-6)}</p>
              </div>
              <button onClick={handleDisconnect} className="btn-secondary">
                Disconnect
              </button>
            </div>
          )}
        </section>

        {/* Wrong Network Warning */}
        {isWrongNetwork && (
          <div style={{
            padding: '1rem',
            marginBottom: '1.5rem',
            backgroundColor: 'rgba(244, 67, 54, 0.1)',
            border: '2px solid #f44336',
            borderRadius: '12px',
          }}>
            <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem', marginBottom: '0.5rem' }}>
              <span style={{ fontSize: '1.5rem' }}>⚠️</span>
              <strong style={{ fontSize: '1.125rem', color: '#f44336' }}>Wrong Network Detected</strong>
            </div>
            <p style={{ marginBottom: '0.75rem', fontSize: '0.95rem' }}>
              You're connected to <strong>{chain?.name || 'Unknown Network'}</strong> (Chain ID: {chain?.id}).
              <br />
              This app requires <strong>{expectedNetworkName}</strong>.
            </p>
            <p style={{ marginBottom: '0.75rem', fontSize: '0.95rem' }}>
              Please disconnect and reconnect with the correct network selected in your wallet.
            </p>
            <button onClick={handleDisconnect} className="btn-primary" style={{ fontSize: '0.95rem', padding: '0.75rem 1.5rem' }}>
              Disconnect Wallet
            </button>
          </div>
        )}

        {/* FHEVM Status */}
        {isConnected && !isWrongNetwork && (
          <section className="section">
            <h2>2. FHEVM Initialization</h2>
            <div className="status-badge">
              <span style={{ fontSize: '1.25rem' }}>
                {status === FhevmClientStatus.READY ? '✓' : status === FhevmClientStatus.ERROR ? '✗' : '⏳'}
              </span>
              <span className={status === FhevmClientStatus.READY ? 'status-ready' : 'status-loading'}>
                {status === FhevmClientStatus.READY ? 'Ready' : status === FhevmClientStatus.ERROR ? 'Error' : 'Loading...'}
              </span>
            </div>
          </section>
        )}

        {/* Counter Demo */}
        {isConnected && !isWrongNetwork && isReady && (
          <section className="section">
            <h2>3. Encrypted Counter Demo</h2>
            <p style={{ marginBottom: '1.5rem', fontSize: '0.95rem' }}>
              Interact with encrypted data on the blockchain using FHE.
            </p>

            {/* Transaction Status */}
            {txStatus && (
              <div style={{ 
                padding: '1rem', 
                marginBottom: '1.5rem', 
                backgroundColor: txStatus.startsWith('✓') ? 'rgba(76, 175, 80, 0.1)' : txStatus.startsWith('✗') ? 'rgba(244, 67, 54, 0.1)' : 'rgba(255, 193, 7, 0.1)',
                border: `2px solid ${txStatus.startsWith('✓') ? '#4CAF50' : txStatus.startsWith('✗') ? '#f44336' : '#FFC107'}`,
                borderRadius: '8px',
                textAlign: 'center',
                fontWeight: 500
              }}>
                {txStatus}
              </div>
            )}

            {/* User Counter (Private Decryption) */}
            <div style={{ marginBottom: '2rem', padding: '1.5rem', backgroundColor: 'rgba(0,0,0,0.1)', borderRadius: '8px' }}>
              <h3 style={{ marginTop: 0, marginBottom: '0.5rem' }}>👤 User Counter (Private)</h3>
              <p style={{ fontSize: '0.875rem', opacity: 0.8, marginBottom: '1rem' }}>
                Only you can decrypt this value using <code style={{ backgroundColor: 'rgba(0,0,0,0.2)', padding: '2px 6px', borderRadius: '4px' }}>userDecrypt()</code>
              </p>
              <div style={{ display: 'flex', gap: '0.75rem', alignItems: 'center', marginBottom: '1rem' }}>
                <button 
                  className="btn-primary" 
                  onClick={() => handleIncrement('user')}
                  disabled={loading === 'increment-user'}
                >
                  {loading === 'increment-user' ? 'Incrementing...' : 'Increment User Counter'}
                </button>
                <button 
                  className="btn-secondary" 
                  onClick={handleDecryptUser}
                  disabled={loading === 'decrypt-user'}
                >
                  {loading === 'decrypt-user' ? 'Decrypting...' : 'Decrypt My Value'}
                </button>
              </div>
              <div style={{ padding: '1rem', backgroundColor: 'rgba(255,255,255,0.1)', borderRadius: '6px' }}>
                <p style={{ margin: 0, fontSize: '0.875rem' }}>
                  Decrypted Value: <strong style={{ fontSize: '1.25rem' }}>{userValue}</strong>
                </p>
              </div>
            </div>

            {/* Public Counter (Public Decryption) */}
            <div style={{ padding: '1.5rem', backgroundColor: 'rgba(0,0,0,0.1)', borderRadius: '8px' }}>
              <h3 style={{ marginTop: 0, marginBottom: '0.5rem' }}>🌍 Public Counter</h3>
              <p style={{ fontSize: '0.875rem', opacity: 0.8, marginBottom: '1rem' }}>
                Anyone can decrypt this value using <code style={{ backgroundColor: 'rgba(0,0,0,0.2)', padding: '2px 6px', borderRadius: '4px' }}>publicDecrypt()</code>
              </p>
              <div style={{ display: 'flex', gap: '0.75rem', alignItems: 'center', marginBottom: '1rem' }}>
                <button 
                  className="btn-primary" 
                  onClick={() => handleIncrement('public')}
                  disabled={loading === 'increment-public'}
                >
                  {loading === 'increment-public' ? 'Incrementing...' : 'Increment Public Counter'}
                </button>
                <button 
                  className="btn-secondary" 
                  onClick={handleDecryptPublic}
                  disabled={loading === 'decrypt-public'}
                >
                  {loading === 'decrypt-public' ? 'Decrypting...' : 'Decrypt Public Value'}
                </button>
              </div>
              <div style={{ padding: '1rem', backgroundColor: 'rgba(255,255,255,0.1)', borderRadius: '6px' }}>
                <p style={{ margin: 0, fontSize: '0.875rem' }}>
                  Decrypted Value: <strong style={{ fontSize: '1.25rem' }}>{publicValue}</strong>
                </p>
              </div>
            </div>
          </section>
        )}
      </div>
    </main>
  );
}

// examples/vue/src/App.vue
<script setup lang="ts">
import { ref, onMounted, computed } from 'vue';
import { BrowserWalletConnector, useVueDapp } from '@vue-dapp/core';
import { VueDappModal, useVueDappModal } from '@vue-dapp/modal';
import { useFhevm, useFhevmEncrypt, useFhevmPublicDecrypt, useFhevmUserDecrypt, FhevmClientStatus, FhevmCacheType } from '@fhevm/vue-sdk';
import '@vue-dapp/modal/dist/style.css';
import { NETWORK_MODE } from './config';
import { LOCALHOST_COUNTER_ADDRESS } from './config/localhost';
import { SEPOLIA_COUNTER_ADDRESS } from './config/sepolia';
import { sendIncrementTx, getPublicCounterHandle, getUserCounterHandle } from '@/lib/contracts/counter';

const { addConnectors, isConnected, wallet, disconnect } = useVueDapp();
const { open } = useVueDappModal();

// FHEVM client from plugin
const { status, isReady, network } = useFhevm();

// Network validation
const expectedChainId = NETWORK_MODE === 'localhost' ? 31337 : 11155111; // Localhost: 31337, Sepolia: 11155111
const isWrongNetwork = computed(() => {
  // Debug logging
  console.log('Vue Network Debug:', {
    isConnected: isConnected.value,
    wallet: wallet,
    chainId: wallet.chainId,
    expectedChainId
  });
  return isConnected.value && wallet.chainId && wallet.chainId !== expectedChainId;
});
const expectedNetworkName = NETWORK_MODE === 'localhost' ? 'Localhost (31337)' : 'Sepolia Testnet';
  
// Contract address based on network
const contractAddress = NETWORK_MODE === 'localhost' ? LOCALHOST_COUNTER_ADDRESS : SEPOLIA_COUNTER_ADDRESS;

// Encryption and decryption hooks
const { createInput } = useFhevmEncrypt({ contractAddress });
const { decrypt: publicDecrypt } = useFhevmPublicDecrypt();
const { decrypt: userDecrypt, clearCache } = useFhevmUserDecrypt({ contractAddress, cacheType: FhevmCacheType.Persistent });

// Add wallet connectors on mount
onMounted(() => {
  addConnectors([
    new BrowserWalletConnector(),
  ]);
});

// Mock state for demo
const userValue = ref<string>('-');
const publicValue = ref<string>('-');
const loading = ref<string>('');
const txStatus = ref<string>('');

// Computed status text
const statusText = computed(() => {
  if (status.value === FhevmClientStatus.LOADING) return 'Loading...';
  if (status.value === FhevmClientStatus.READY) return 'Ready ✓';
  if (status.value === FhevmClientStatus.ERROR) return 'Error';
  return 'Idle';
});

// Handlers
const handleIncrement = async (type: 'user' | 'public') => {
  try {
    // Set loading state first and force UI update
    loading.value = `increment-${type}`;
    txStatus.value = '⏳ Encrypting value...';
    
    // Small delay to ensure UI updates before encryption starts
    await new Promise(resolve => setTimeout(resolve, 0));

    if (!wallet.address) {
      throw new Error('Wallet not connected');
    }

    // Create encrypted input
    const input = createInput(wallet.address);
    input.add32(1);
    const encrypted = await input.encrypt();

    txStatus.value = '⏳ Sending transaction...';
    await sendIncrementTx(encrypted.handles[0], encrypted.inputProof, type, NETWORK_MODE);

    txStatus.value = `✓ ${type === 'public' ? 'Public' : 'User'} counter incremented!`;
    setTimeout(() => { txStatus.value = ''; }, 3000);
  } catch (error) {
    console.error('Increment error:', error);
    txStatus.value = `✗ Error: ${error instanceof Error ? error.message : 'Unknown error'}`;
    setTimeout(() => { txStatus.value = ''; }, 3000);
  } finally {
    loading.value = '';
  }
};

const handleDecryptUser = async () => {
  try {
    loading.value = 'decrypt-user';
    userValue.value = '⏳ Decrypting...';
    const handle = await getUserCounterHandle(NETWORK_MODE);
    const decryptedValue = await userDecrypt(handle, wallet);
    userValue.value = decryptedValue.toString();
  } catch (error) {
    console.error('Decrypt user error:', error);
    userValue.value = '✗ Error';
  } finally {
    loading.value = '';
  }
};

const handleDecryptPublic = async () => {
  try {
    loading.value = 'decrypt-public';
    publicValue.value = '⏳ Decrypting...';
    const handle = await getPublicCounterHandle(NETWORK_MODE);
    const decryptedValue = await publicDecrypt(handle);
    publicValue.value = decryptedValue.toString();
  } catch (error) {
    console.error('Decrypt public error:', error);
    publicValue.value = '✗ Error';
  } finally {
    loading.value = '';
  }
};

// Disconnect handler with cache clearing
const handleDisconnect = async () => {
  // Clear signature cache on disconnect
  await clearCache();
  disconnect();
};

// Connect/disconnect handlers
const handleConnectClick = () => {
  if (isConnected.value) {
    handleDisconnect();
  } else {
    open();
  }
};
</script>

<template>
  <main class="container">
    <div class="card">
      <h1 style="text-align: center">FHEVM SDK Vue Demo</h1>
      <p class="subtitle">
        Build confidential applications with Fully Homomorphic Encryption
      </p>
      <p style="text-align: center; font-size: 0.875rem; opacity: 0.7; margin-top: 0.5rem">
        Network: <strong>{{ network === 'localhost' ? 'Localhost' : 'Sepolia' }}</strong>
      </p>
      
      <!-- Wallet Connection -->
      <section class="section">
        <h2>1. Connect Wallet</h2>
        <button 
          v-if="!isConnected"
          @click="handleConnectClick"
          class="btn-primary"
        >
          Connect Wallet
        </button>
        <div v-else class="wallet-info">
          <div style="flex: 1">
            <p style="margin-bottom: 0.25rem; font-size: 0.875rem; opacity: 0.7">Connected Address</p>
            <p class="wallet-address">{{ wallet.address?.slice(0, 8) }}...{{ wallet.address?.slice(-6) }}</p>
          </div>
          <button @click="handleConnectClick" class="btn-secondary">
            Disconnect
          </button>
        </div>
      </section>

      <!-- Wrong Network Warning -->
      <div 
        v-if="isWrongNetwork"
        style="
          padding: 1rem;
          margin-bottom: 1.5rem;
          background-color: rgba(244, 67, 54, 0.1);
          border: 2px solid #f44336;
          border-radius: 12px;
        "
      >
        <div style="display: flex; align-items: center; gap: 0.5rem; margin-bottom: 0.5rem">
          <span style="font-size: 1.5rem">⚠️</span>
          <strong style="font-size: 1.125rem; color: #f44336">Wrong Network Detected</strong>
        </div>
        <p style="margin-bottom: 0.75rem; font-size: 0.95rem">
          You're connected to <strong>{{ wallet.chainId === 1 ? 'Ethereum Mainnet' : `Chain ID ${wallet.chainId}` }}</strong>.
          <br />
          This app requires <strong>{{ expectedNetworkName }}</strong>.
        </p>
        <p style="margin-bottom: 0.75rem; font-size: 0.95rem">
          Please disconnect and reconnect with the correct network selected in your wallet.
        </p>
        <button @click="handleConnectClick" class="btn-primary" style="font-size: 0.95rem; padding: 0.75rem 1.5rem">
          Disconnect Wallet
        </button>
      </div>
  
      <!-- FHEVM Status -->
      <section v-if="isConnected && !isWrongNetwork" class="section">
        <h2>2. FHEVM Initialization</h2>
        <div class="status-badge">
          <span :class="isReady ? 'status-ready' : 'status-loading'">
            {{ statusText }}
          </span>
        </div>
      </section>

      <!-- Counter Demo -->
      <section v-if="isConnected && !isWrongNetwork && isReady" class="section">
        <h2>3. Encrypted Counter Demo</h2>
        <p style="margin-bottom: 1.5rem; font-size: 0.95rem">
          Interact with encrypted data on the blockchain using FHE.
        </p>

        <!-- Transaction Status -->
        <div 
          v-if="txStatus"
          :style="{ 
            padding: '1rem', 
            marginBottom: '1.5rem', 
            backgroundColor: txStatus.startsWith('✓') ? 'rgba(76, 175, 80, 0.1)' : txStatus.startsWith('✗') ? 'rgba(244, 67, 54, 0.1)' : 'rgba(255, 193, 7, 0.1)',
            border: `2px solid ${txStatus.startsWith('✓') ? '#4CAF50' : txStatus.startsWith('✗') ? '#f44336' : '#FFC107'}`,
            borderRadius: '8px',
            textAlign: 'center',
            fontWeight: 500
          }"
        >
          {{ txStatus }}
        </div>

        <!-- User Counter (Private Decryption) -->
        <div style="margin-bottom: 2rem; padding: 1.5rem; background-color: rgba(0,0,0,0.1); border-radius: 8px">
          <h3 style="margin-top: 0; margin-bottom: 0.5rem">👤 User Counter (Private)</h3>
          <p style="font-size: 0.875rem; opacity: 0.8; margin-bottom: 1rem">
            Only you can decrypt this value using <code style="background-color: rgba(0,0,0,0.2); padding: 2px 6px; border-radius: 4px">userDecrypt()</code>
          </p>
          <div style="display: flex; gap: 0.75rem; align-items: center; margin-bottom: 1rem">
            <button 
              class="btn-primary" 
              @click="handleIncrement('user')"
              :disabled="loading === 'increment-user'"
            >
              {{ loading === 'increment-user' ? 'Incrementing...' : 'Increment User Counter' }}
            </button>
            <button 
              class="btn-secondary" 
              @click="handleDecryptUser"
              :disabled="loading === 'decrypt-user'"
            >
              {{ loading === 'decrypt-user' ? 'Decrypting...' : 'Decrypt My Value' }}
            </button>
          </div>
          <div style="padding: 1rem; background-color: rgba(255,255,255,0.1); border-radius: 6px">
            <p style="margin: 0; font-size: 0.875rem">
              Decrypted Value: <strong style="font-size: 1.25rem">{{ userValue }}</strong>
            </p>
          </div>
        </div>

        <!-- Public Counter (Public Decryption) -->
        <div style="padding: 1.5rem; background-color: rgba(0,0,0,0.1); border-radius: 8px">
          <h3 style="margin-top: 0; margin-bottom: 0.5rem">🌍 Public Counter</h3>
          <p style="font-size: 0.875rem; opacity: 0.8; margin-bottom: 1rem">
            Anyone can decrypt this value using <code style="background-color: rgba(0,0,0,0.2); padding: 2px 6px; border-radius: 4px">publicDecrypt()</code>
          </p>
          <div style="display: flex; gap: 0.75rem; align-items: center; margin-bottom: 1rem">
            <button 
              class="btn-primary" 
              @click="handleIncrement('public')"
              :disabled="loading === 'increment-public'"
            >
              {{ loading === 'increment-public' ? 'Incrementing...' : 'Increment Public Counter' }}
            </button>
            <button 
              class="btn-secondary" 
              @click="handleDecryptPublic"
              :disabled="loading === 'decrypt-public'"
            >
              {{ loading === 'decrypt-public' ? 'Decrypting...' : 'Decrypt Public Value' }}
            </button>
          </div>
          <div style="padding: 1rem; background-color: rgba(255,255,255,0.1); border-radius: 6px">
            <p style="margin: 0; font-size: 0.875rem">
              Decrypted Value: <strong style="font-size: 1.25rem">{{ publicValue }}</strong>
            </p>
          </div>
        </div>
      </section>
    </div>

    <!-- VueDapp Modal for wallet selection -->
    <VueDappModal dark auto-connect />
  </main>
</template>
